language: objective-c
osx_image: xcode10.2

before_cache:
  - brew cleanup

cache:
  directories:
    - src/Pods
    - $HOME/Library/Caches/Homebrew

before_install:
  - curl -o src/TheMessagesApp/GoogleService-Info.plist -X GET "https://firebasestorage.googleapis.com/v0/b/messages-3d119.appspot.com/o/app-config%2FGoogleService-Info.plist?alt=media&token=${FIREBASE_CONFIG_FILE_TOKEN}"
  - gem install cocoapods --pre
  - pod repo update
  - cd src
  - brew install xcodegen
  - bundle install
  - xcodegen
  - pod install

install:
  - fastlane tests
