language: objective-c
osx_image: xcode10.2

# podfile: src/Podfile
xcode_workspace: TheMessagesApp.xcworkspace
xcode_scheme: TheMessagesApp
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone SE

before_cache:
  - brew cleanup

cache:
  directories:
    - src/Pods
    - $HOME/Library/Caches/Homebrew

before_install:
  - cd src
  - curl -o TheMessagesApp/GoogleService-Info.plist -X GET "https://firebasestorage.googleapis.com/v0/b/messages-3d119.appspot.com/o/app-config%2FGoogleService-Info.plist?alt=media&token=${FIREBASE_CONFIG_FILE_TOKEN}"
  - gem install cocoapods --pre
  - pod repo update
  - brew install xcodegen
  - bundle install
  - xcodegen
  - pod install
  # - cd ..

# install:
#   - fastlane tests
