language: objective-c
osx_image: xcode10.2
podfile: src/Podfile
xcode_workspace: src/TheMessageApp.xcworkspace
xcode_scheme: TheMessageApp
xcode_destination: platform=iOS Simulator,OS=10.0,name=iPhone SE

before_install:
  - curl -o src/TheMessageApp/GoogleService-Info.plist -X GET "https://firebasestorage.googleapis.com/v0/b/messages-3d119.appspot.com/o/app-config%2FGoogleService-Info.plist?alt=media&token=${FIREBASE_CONFIG_FILE_TOKEN}"
  - gem install cocoapods --pre
  - pod repo update
  - brew install xcodegen
  - cd src
  - xcodegen
