name: TheMessagesApp
options:
  bundleIdPrefix: com.jabaridash
targets:
  TheMessagesApp:
    type: application
    platform: iOS
    deploymentTarget: "10.0"
    sources: [TheMessagesApp]
    dependencies:
      - sdk: libc++.tbd
  TheMessagesAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "10.0"
    sources:
      - path: TheMessagesAppTests
    dependencies:
      - target: TheMessagesApp
