name: TheMessagesApp
options:
  bundleIdPrefix: com.jabaridash
targets:
  TheMessagesApp:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: [TheMessagesApp]
    dependencies:
      - sdk: libc++.tbd
    settings:
      DEVELOPMENT_TEAM: 62TYL29D89
  TheMessagesAppTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "11.0"
    sources:
      - path: TheMessagesAppTests
    dependencies:
      - target: TheMessagesApp
